# Generated by Django 5.1.6 on 2025-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
