# Generated by Django 5.1.6 on 2025-03-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_project_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
